apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  labels:
    app: {{ template "app.name" . }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: http
    port: {{ .Values.port}} 
    targetPort: {{ .Values.port}} 
    protocol: TCP
  selector:
    app: {{ template "app.name" . }}